### ISSUE TITLE
Question about PR - SOSL

### ISSUE THREAD

**Issue by davidGravityLab** [SalesforceLabs/Data-Fetcher#3]
We're looking to enhance this to include a SOSL and knowledge SOSL option for our own use. Is this something that would be useful in the base package if we do a PR, or are you looking to keep this tool really simple?

**Comment by jdayment** [comment]
I have SOSL on my roadmap but it's going to require a CPE that I am about 70% completed on the intention is to keep very simple config and without a CPE it can get confusing.
